//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamSpur
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_tblmerchantUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_tblmerchantUser()
        {
            this.C_tblMerchantUsage = new HashSet<C_tblMerchantUsage>();
        }
    
        public int Userid { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public Nullable<int> role { get; set; }
        public Nullable<System.DateTime> regdate { get; set; }
        public Nullable<long> merchantid { get; set; }
        public Nullable<bool> status { get; set; }
        public string password { get; set; }
    
        public virtual C_tblMerchant C_tblMerchant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_tblMerchantUsage> C_tblMerchantUsage { get; set; }
    }
}
