//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamSpur
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_tblSubjectGeneral
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_tblSubjectGeneral()
        {
            this.C_tblQuestion = new HashSet<C_tblQuestion>();
            this.C_tblQuestionList = new HashSet<C_tblQuestionList>();
            this.C_tblQuestionUTMETrial = new HashSet<C_tblQuestionUTMETrial>();
            this.C_tblQuestionWAEC = new HashSet<C_tblQuestionWAEC>();
            this.C_tblQuestionWAECTrial = new HashSet<C_tblQuestionWAECTrial>();
            this.C_tblScore = new HashSet<C_tblScore>();
            this.C_tblTopics = new HashSet<C_tblTopics>();
        }
    
        public int SubjectID { get; set; }
        public string SubjectName { get; set; }
        public int Duration { get; set; }
        public int ExamID { get; set; }
        public Nullable<int> NoOfQuestions { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_tblQuestion> C_tblQuestion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_tblQuestionList> C_tblQuestionList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_tblQuestionUTMETrial> C_tblQuestionUTMETrial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_tblQuestionWAEC> C_tblQuestionWAEC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_tblQuestionWAECTrial> C_tblQuestionWAECTrial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_tblScore> C_tblScore { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_tblTopics> C_tblTopics { get; set; }
    }
}
