//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamSpur
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_tblMerchant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_tblMerchant()
        {
            this.C_tblclass = new HashSet<C_tblclass>();
            this.C_tblMerchantUsage = new HashSet<C_tblMerchantUsage>();
            this.C_tblmerchantUser = new HashSet<C_tblmerchantUser>();
            this.C_tblStudentReg = new HashSet<C_tblStudentReg>();
            this.C_tblStudentUsage = new HashSet<C_tblStudentUsage>();
            this.C_tblSubscription = new HashSet<C_tblSubscription>();
        }
    
        public long MerchantID { get; set; }
        public string CenterName { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Password { get; set; }
        public string Salt { get; set; }
        public System.DateTime RegDate { get; set; }
        public Nullable<int> stateId { get; set; }
        public string city { get; set; }
        public Nullable<int> UnitAvailable { get; set; }
        public string RefCode { get; set; }
        public Nullable<System.DateTime> Expdate { get; set; }
        public string logo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_tblclass> C_tblclass { get; set; }
        public virtual C_tblstate C_tblstate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_tblMerchantUsage> C_tblMerchantUsage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_tblmerchantUser> C_tblmerchantUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_tblStudentReg> C_tblStudentReg { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_tblStudentUsage> C_tblStudentUsage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_tblSubscription> C_tblSubscription { get; set; }
    }
}
