//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamSpur
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_tblSubjectSchoolBased
    {
        public int SubjectID { get; set; }
        public string SubjectName { get; set; }
        public int Duration { get; set; }
        public int ExamID { get; set; }
        public int SchoolID { get; set; }
        public Nullable<int> NoOfQuestions { get; set; }
    
        public virtual C_tblSchool C_tblSchool { get; set; }
    }
}
