//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamSpur
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_tblMerchantUsage
    {
        public long ID { get; set; }
        public long MerchantID { get; set; }
        public long StudentID { get; set; }
        public byte[] AssignedDate { get; set; }
        public Nullable<int> MerchantUserID { get; set; }
        public Nullable<int> Unit { get; set; }
    
        public virtual C_tblMerchant C_tblMerchant { get; set; }
        public virtual C_tblmerchantUser C_tblmerchantUser { get; set; }
        public virtual C_tblStudentReg C_tblStudentReg { get; set; }
    }
}
