//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamSpur
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_tblQuestionList
    {
        public long QuestionListID { get; set; }
        public int ExamID { get; set; }
        public int SubjectID { get; set; }
        public string QuestionList { get; set; }
        public Nullable<int> TimeElapsed { get; set; }
        public int LastQuestionID { get; set; }
        public Nullable<long> ExamTakenId { get; set; }
        public string CorrectAnswerList { get; set; }
        public string ChoosenAnswerList { get; set; }
        public string IncorrectAnswerList { get; set; }
        public Nullable<int> NoAttempted { get; set; }
        public Nullable<int> NoCorrect { get; set; }
    
        public virtual C_tblExamTaken C_tblExamTaken { get; set; }
        public virtual C_tblExamType C_tblExamType { get; set; }
        public virtual C_tblSubjectGeneral C_tblSubjectGeneral { get; set; }
    }
}
