//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamSpur
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_tblPayout
    {
        public int PayoutID { get; set; }
        public Nullable<System.DateTime> Paydate { get; set; }
        public Nullable<System.Guid> marketerid { get; set; }
        public Nullable<decimal> Commission { get; set; }
        public Nullable<decimal> Transport { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string PaymentRef { get; set; }
    
        public virtual C_tblMarketer C_tblMarketer { get; set; }
    }
}
