//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamSpur
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_tblSubscription
    {
        public long SubscriptionID { get; set; }
        public System.DateTime SubscriptionDate { get; set; }
        public Nullable<long> StudentID { get; set; }
        public Nullable<long> MerchantID { get; set; }
        public string paymentRef { get; set; }
        public Nullable<short> PlanID { get; set; }
        public Nullable<bool> paymentStatus { get; set; }
        public string Username { get; set; }
        public Nullable<int> Unit { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> AgentStatus { get; set; }
        public string RefCode { get; set; }
    
        public virtual C_tblMerchant C_tblMerchant { get; set; }
        public virtual C_tblStudentReg C_tblStudentReg { get; set; }
        public virtual C_tblSubscriptionPlan C_tblSubscriptionPlan { get; set; }
    }
}
