//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamSpur
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_tblMarketer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_tblMarketer()
        {
            this.C_tblPayout = new HashSet<C_tblPayout>();
            this.MarketerPaylists = new HashSet<MarketerPaylist>();
        }
    
        public System.Guid MarketerID { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public Nullable<int> stateId { get; set; }
        public string email { get; set; }
        public string phoneno { get; set; }
        public string address { get; set; }
        public Nullable<System.DateTime> regdate { get; set; }
        public Nullable<bool> status { get; set; }
        public string referralcode { get; set; }
        public string password { get; set; }
        public string accountno { get; set; }
        public string bankcode { get; set; }
        public string BankAccountName { get; set; }
        public Nullable<short> partnerType { get; set; }
        public string CenterName { get; set; }
    
        public virtual C_tblbank C_tblbank { get; set; }
        public virtual C_tblstate C_tblstate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_tblPayout> C_tblPayout { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MarketerPaylist> MarketerPaylists { get; set; }
    }
}
