//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamSpur
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_tblScore
    {
        public long ScoreID { get; set; }
        public long ExamCode { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public int Score { get; set; }
        public long StudentID { get; set; }
        public Nullable<int> ExamID { get; set; }
    
        public virtual C_tblExamTaken C_tblExamTaken { get; set; }
        public virtual C_tblExamType C_tblExamType { get; set; }
        public virtual C_tblStudentReg C_tblStudentReg { get; set; }
        public virtual C_tblSubjectGeneral C_tblSubjectGeneral { get; set; }
    }
}
