//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamSpur
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_tblSubscriptionPlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_tblSubscriptionPlan()
        {
            this.C_tblSubscription = new HashSet<C_tblSubscription>();
        }
    
        public short Id { get; set; }
        public string PlanType { get; set; }
        public Nullable<decimal> PlanAmount { get; set; }
        public Nullable<int> UserType { get; set; }
        public string PlanRange { get; set; }
        public Nullable<int> Unit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_tblSubscription> C_tblSubscription { get; set; }
    }
}
