//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamSpur
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_tblStudentUsage
    {
        public long StudentID { get; set; }
        public byte[] UsedDate { get; set; }
        public Nullable<long> MerchantID { get; set; }
        public int ID { get; set; }
    
        public virtual C_tblMerchant C_tblMerchant { get; set; }
        public virtual C_tblStudentReg C_tblStudentReg { get; set; }
    }
}
