//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamSpur
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_tblExamTaken
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_tblExamTaken()
        {
            this.C_tblQuestionList = new HashSet<C_tblQuestionList>();
            this.C_tblQuestionListTopic = new HashSet<C_tblQuestionListTopic>();
            this.C_tblScore = new HashSet<C_tblScore>();
        }
    
        public long ExamTakenID { get; set; }
        public long StudentID { get; set; }
        public int ExamID { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> StartTimestamp { get; set; }
        public Nullable<System.DateTime> EndTimestamp { get; set; }
        public Nullable<int> TimeUsed { get; set; }
        public Nullable<int> TotalTime { get; set; }
        public Nullable<int> ExamMode { get; set; }
        public Nullable<int> ActiveSubject { get; set; }
    
        public virtual C_tblStudentReg C_tblStudentReg { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_tblQuestionList> C_tblQuestionList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_tblQuestionListTopic> C_tblQuestionListTopic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_tblScore> C_tblScore { get; set; }
    }
}
