//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamSpur
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_tblStudentReg
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_tblStudentReg()
        {
            this.C_tblExamTaken = new HashSet<C_tblExamTaken>();
            this.C_tblMerchantUsage = new HashSet<C_tblMerchantUsage>();
            this.C_tblScore = new HashSet<C_tblScore>();
            this.C_tblStudentUsage = new HashSet<C_tblStudentUsage>();
            this.C_tblSubscription = new HashSet<C_tblSubscription>();
        }
    
        public long StudentID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Gender { get; set; }
        public System.DateTime RegDate { get; set; }
        public string Phone { get; set; }
        public Nullable<long> MerchantID { get; set; }
        public Nullable<int> Unit { get; set; }
        public Nullable<bool> Status { get; set; }
        public string secretPin { get; set; }
        public string RefCode { get; set; }
        public Nullable<int> ClassID { get; set; }
    
        public virtual C_tblclass C_tblclass { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_tblExamTaken> C_tblExamTaken { get; set; }
        public virtual C_tblMerchant C_tblMerchant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_tblMerchantUsage> C_tblMerchantUsage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_tblScore> C_tblScore { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_tblStudentUsage> C_tblStudentUsage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_tblSubscription> C_tblSubscription { get; set; }
    }
}
