//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamSpur
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_tblTopics
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_tblTopics()
        {
            this.C_tblQuestion = new HashSet<C_tblQuestion>();
            this.C_tblQuestionListTopic = new HashSet<C_tblQuestionListTopic>();
            this.C_tblQuestionWAEC = new HashSet<C_tblQuestionWAEC>();
        }
    
        public int TopicId { get; set; }
        public string TopicName { get; set; }
        public int SubjectId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_tblQuestion> C_tblQuestion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_tblQuestionListTopic> C_tblQuestionListTopic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_tblQuestionWAEC> C_tblQuestionWAEC { get; set; }
        public virtual C_tblSubjectGeneral C_tblSubjectGeneral { get; set; }
    }
}
