//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamSpur
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EXAMSPURDBEntities : DbContext
    {
        public EXAMSPURDBEntities()
            : base("name=EXAMSPURDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_ExamGroup> C_ExamGroup { get; set; }
        public virtual DbSet<C_tblbank> C_tblbank { get; set; }
        public virtual DbSet<C_tblclass> C_tblclass { get; set; }
        public virtual DbSet<C_tblExamTaken> C_tblExamTaken { get; set; }
        public virtual DbSet<C_tblExamType> C_tblExamType { get; set; }
        public virtual DbSet<C_tblLogin> C_tblLogin { get; set; }
        public virtual DbSet<C_tblMarketer> C_tblMarketer { get; set; }
        public virtual DbSet<C_tblMerchant> C_tblMerchant { get; set; }
        public virtual DbSet<C_tblMerchantUsage> C_tblMerchantUsage { get; set; }
        public virtual DbSet<C_tblmerchantUser> C_tblmerchantUser { get; set; }
        public virtual DbSet<C_tblPayout> C_tblPayout { get; set; }
        public virtual DbSet<C_tblQuestion> C_tblQuestion { get; set; }
        public virtual DbSet<C_tblQuestionList> C_tblQuestionList { get; set; }
        public virtual DbSet<C_tblQuestionListTopic> C_tblQuestionListTopic { get; set; }
        public virtual DbSet<C_tblQuestionUTMETrial> C_tblQuestionUTMETrial { get; set; }
        public virtual DbSet<C_tblQuestionWAEC> C_tblQuestionWAEC { get; set; }
        public virtual DbSet<C_tblQuestionWAECTrial> C_tblQuestionWAECTrial { get; set; }
        public virtual DbSet<C_tblSchool> C_tblSchool { get; set; }
        public virtual DbSet<C_tblScore> C_tblScore { get; set; }
        public virtual DbSet<C_tblstate> C_tblstate { get; set; }
        public virtual DbSet<C_tblStudentReg> C_tblStudentReg { get; set; }
        public virtual DbSet<C_tblStudentUsage> C_tblStudentUsage { get; set; }
        public virtual DbSet<C_tblSubjectGeneral> C_tblSubjectGeneral { get; set; }
        public virtual DbSet<C_tblSubjectSchoolBased> C_tblSubjectSchoolBased { get; set; }
        public virtual DbSet<C_tblSubscription> C_tblSubscription { get; set; }
        public virtual DbSet<C_tblSubscriptionPlan> C_tblSubscriptionPlan { get; set; }
        public virtual DbSet<C_tblTopics> C_tblTopics { get; set; }
        public virtual DbSet<MarketerPaylist> MarketerPaylists { get; set; }
        public virtual DbSet<PayoutPartner> PayoutPartners { get; set; }
        public virtual DbSet<tableMailAlert> tableMailAlerts { get; set; }
        public virtual DbSet<tblNewExamTaken> tblNewExamTakens { get; set; }
        public virtual DbSet<tblNewQuestion> tblNewQuestions { get; set; }
        public virtual DbSet<tblNewQuestionList> tblNewQuestionLists { get; set; }
        public virtual DbSet<tblNewScore> tblNewScores { get; set; }
        public virtual DbSet<tblNewStudentRecord> tblNewStudentRecords { get; set; }
        public virtual DbSet<tblNewSubjectGeneral> tblNewSubjectGenerals { get; set; }
        public virtual DbSet<tblPinSubscription> tblPinSubscriptions { get; set; }
    }
}
