//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamSpur
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarketerPaylist
    {
        public int paylistid { get; set; }
        public Nullable<long> userid { get; set; }
        public Nullable<short> usertype { get; set; }
        public System.Guid marketerid { get; set; }
        public Nullable<System.DateTime> subdate { get; set; }
        public Nullable<decimal> commission { get; set; }
        public Nullable<decimal> transport { get; set; }
    
        public virtual C_tblMarketer C_tblMarketer { get; set; }
    }
}
