//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamSpur
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NewExamspurDBEntities2 : DbContext
    {
        public NewExamspurDBEntities2()
            : base("name=NewExamspurDBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblNewSubjectGeneral> tblNewSubjectGenerals { get; set; }
        public virtual DbSet<tblNewExamTaken> tblNewExamTakens { get; set; }
        public virtual DbSet<tblNewQuestionList> tblNewQuestionLists { get; set; }
        public virtual DbSet<tblNewScore> tblNewScores { get; set; }
        public virtual DbSet<tblNewStudentRecord> tblNewStudentRecords { get; set; }
        public virtual DbSet<tblNewQuestion> tblNewQuestions { get; set; }
    }
}
