//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamSpur
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayoutPartner
    {
        public int PayoutPartnersID { get; set; }
        public Nullable<System.DateTime> Paydate { get; set; }
        public Nullable<int> PayeeID { get; set; }
        public Nullable<decimal> AmountPaidOut { get; set; }
        public string PaymentRef { get; set; }
        public Nullable<decimal> TotalRevenue { get; set; }
    }
}
