//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamSpur
{
    using System;
    using System.Collections.Generic;
    
    public partial class tableMailAlert
    {
        public long ID { get; set; }
        public string subject { get; set; }
        public string body { get; set; }
        public string receiverEmail { get; set; }
        public Nullable<System.DateTime> dropTimestamp { get; set; }
        public Nullable<System.DateTime> sentTimestamp { get; set; }
        public Nullable<int> status { get; set; }
        public string header1 { get; set; }
        public string header2 { get; set; }
    }
}
