//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamSpur
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNewScore
    {
        public long ScoreID { get; set; }
        public long ExamCode { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public int Score { get; set; }
        public long StudentID { get; set; }
        public Nullable<int> ExamID { get; set; }
    
        public virtual tblNewStudentRecord tblNewStudentRecord { get; set; }
        public virtual tblNewSubjectGeneral tblNewSubjectGeneral { get; set; }
    }
}
