//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamSpur
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNewExamTaken
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblNewExamTaken()
        {
            this.tblNewQuestionLists = new HashSet<tblNewQuestionList>();
        }
    
        public long ExamTakenID { get; set; }
        public long StudentID { get; set; }
        public int ExamID { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> StartTimeStamp { get; set; }
        public Nullable<System.DateTime> EndTimeStamp { get; set; }
        public Nullable<int> TimeUsed { get; set; }
        public Nullable<int> TotalTime { get; set; }
        public Nullable<int> ActiveSubject { get; set; }
        public Nullable<int> ExamMode { get; set; }
    
        public virtual tblNewStudentRecord tblNewStudentRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNewQuestionList> tblNewQuestionLists { get; set; }
    }
}
