//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamSpur
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNewQuestionList
    {
        public long QuestionListID { get; set; }
        public int SubjectID { get; set; }
        public string QuestionList { get; set; }
        public Nullable<int> TimeElapsed { get; set; }
        public int LastQuestionID { get; set; }
        public long ExamTakenID { get; set; }
        public string CorrectAnswerList { get; set; }
        public string ChoosenAnswerList { get; set; }
        public string IncorrectAnswerList { get; set; }
        public Nullable<int> NoAttempted { get; set; }
        public Nullable<int> NoCorrect { get; set; }
        public Nullable<int> ExamID { get; set; }
    
        public virtual tblNewExamTaken tblNewExamTaken { get; set; }
        public virtual tblNewSubjectGeneral tblNewSubjectGeneral { get; set; }
    }
}
