//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamSpur
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNewSubjectGeneral
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblNewSubjectGeneral()
        {
            this.tblNewQuestionLists = new HashSet<tblNewQuestionList>();
            this.tblNewScores = new HashSet<tblNewScore>();
        }
    
        public int SubjectID { get; set; }
        public string SubjectName { get; set; }
        public int Duration { get; set; }
        public Nullable<int> ExamID { get; set; }
        public Nullable<int> NoOfQuestion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNewQuestionList> tblNewQuestionLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNewScore> tblNewScores { get; set; }
    }
}
